export const INIT_BOARD = "INIT_BOARD"; // chessboard
export const ADD_MOVE = "ADD_MOVE";
export const SET_POSITIONS = "SET_POSITIONS";
export const HIGHLIGHT_SQUARES = "HIGHLIGHT_SQUARES";
export const UNDO_MOVE = "UNDO_MOVE"; // controls
export const REDO_MOVE = "REDO_MOVE";
export const CLEAR_SQUARES = "CLEAR_SQUARES";
export const UPDATE_SCOREBOARD = "UPDATE_SCOREBOARD";
export const RESET_GAME = "RESET_GAME";
